### ISSUE TITLE
Users can start experiments with no assigned resources

### ISSUE THREAD

**Issue by vs49688** [UQ-RCC/nimrod-portal#3]
As in title.

Job needs to be manually `qdel`'d to stop it.

EDIT: This should probably enforced in the backend too...

**Comment by vs49688** [comment]
Fixed in https://github.com/UQ-RCC/nimrod-portal-backend/commit/b33a2477e75926594330c0557dcfe96eb0e8c3e6

**Comment by hoangnguyen177** [comment]
If there is no assigned resources, control tab is greyed out. 
![image](https://user-images.githubusercontent.com/555847/94888104-63852e00-04bb-11eb-91e9-7cb0d39b9939.png)
