### ISSUE TITLE
Deleting a STOPPED job did not work

### ISSUE THREAD

**Issue by davidcgreen** [UQ-RCC/nimrod-portal#9]
I had created a STOPPED experiment because the software infrastructure was queuing on FlashLite Long queue because the queue was qstop-ped.

Deleting the job did not remove the job from the batch system and so I think it stuck around in portal in STOPPED state.

I have been able to since delete such a job once I had intervened on PBS and deleted the offending job.

**Comment by hoangnguyen177** [comment]
I have made two changes:
* grey out delete button for any experiment that has started
* add a stop button which is only enable when the experiment is started

![image](https://user-images.githubusercontent.com/555847/94887813-9f6bc380-04ba-11eb-8efb-16e4cd22c990.png)
![image](https://user-images.githubusercontent.com/555847/94887895-d04bf880-04ba-11eb-8295-ff3cdfe90f6d.png)
